# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ai-interviews

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://servercontreg.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_3fe9141df33145c6bb67fe225a09f0a8 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_04d9e02959f24985b341ec4266dc26d2 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: servercontreg.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3fe9141df33145c6bb67fe225a09f0a8 }}/aiinterviewsdk:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ai-interviews'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_696588cae68b47caa5f6a755e62b45fb }}
        images: 'servercontreg.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3fe9141df33145c6bb67fe225a09f0a8 }}/aiinterviewsdk:${{ github.sha }}'